[package]
name = "yield_adapter"
description = "A library for creating and managing yield adapters in coopstable."
version = "0.0.0"
authors = ["RasCoder <ftrouw@protonmail.com>"] 
edition = { workspace = true } 
license = { workspace = true }
repository = { workspace = true }

[dependencies]
soroban-sdk = { workspace = true }

[dev-dependencies]
test-case = { workspace = true }

