[package]
name = "blend_capital_adapter"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["lib", "cdylib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }
yield_adapter = { workspace= true, path = "./packages/yield_adapter" }

[dev-dependencies]
test-case =  { workspace = true }
pretty_assertions = { workspace = true }
soroban-sdk = { workspace = true, features = ["testutils"] }

[features]
use_mocks = []
